name: flymusic
description: A new Flutter Music application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.5

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #third party:
  shared_preferences_settings: ^1.0.0+1
  folder_picker: ^0.3.0

  flutter_isolate: ^1.0.0+11

  audioplayers: ^0.14.2

  permission_handler: ^4.2.0+hotfix.3
  archive: ^2.0.13
  flutter_ffmpeg: ^0.2.10

  fluttertoast: ^3.1.3

  provider: ^3.0.0+1

  url_launcher: ^5.4.2
  # Dart
  moor: ^2.4.2
  # Database for mobile and Desktop
  moor_ffi: ^0.4.0

  easy_localization: ^2.0.2

  #dart:
  dart_tags: #forked because of some issues about slow tag reading
    git: git://github.com/Nailik/dart-tags.git


dependency_overrides: #sonst wären folder_picker und shared_preferences_settings inkompatibel und flutter_test
  rxdart: ^0.22.2
  shared_preferences: ^0.5.6+3
  archive: ^2.0.13

dev_dependencies:
  build_runner: ^1.7.3
  build_web_compilers: ^2.3.0
  moor_generator: ^2.4.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/placeholder.jpg
    - asset/images/artist_placeholder.jpg
    - asset/images/linkedin.png
    - asset/langs/en-US.json
    - asset/langs/de-DE.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
